### ISSUE TITLE
TaskThread stack trace from tomcat-util.jar

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-core#214]
at java.lang.Thread.run(Thread.java:829) ~[?:?]
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:9.0.62]
                at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:9.0.62]
                at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:9.0.62]
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:9.0.62]
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) ~[tomcat-coyote.jar:9.0.62]
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) ~[tomcat-coyote.jar:9.0.62]
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-coyote.jar:9.0.62]
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-coyote.jar:9.0.62]

**Comment by AlvaroVega** [comment]
new docker build  https://hub.docker.com/layers/1514432/telefonicaiot/perseo-core/latest/images/sha256-e17f0fc3e44b1874e51962fb822f97a62e492650d74f50a97b6c2ddebbd2903b?context=repo is using tomcat 9.0.63 

25-May-2022 08:10:51.178 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.63
25-May-2022 08:10:51.187 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          May 11 2022 07:52:11 UTC
25-May-2022 08:10:51.187 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.63.0

**Comment by AlvaroVega** [comment]
Some java options where used in a wrong way to achieve this log
